import { type NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import { WebMidi } from 'webmidi'

const Home: NextPage = () => {
  const [enabled, setEnabled] = useState(false)
  const [note, setNote] = useState('')

  WebMidi.enable({ sysex: true })
    .then(() => {
      setEnabled(true)
      startListener()
    })
    .catch((err) => alert(err))

  function startListener() {
    const myInput = WebMidi.getInputByName('Launchpad X LPX MIDI Out')

    if (myInput) {
      myInput.addListener('noteon', (e) => {
        console.log(e.note)
        setNote(e.note.identifier)
      })
      myInput.addListener('noteoff', (e) => {
        console.log(e.note)
        setNote(e.note.identifier)
      })
    } else {
      console.log("Can't Find Device")
    }
  }

  if (enabled) {
    return (
      <>
        <Head>
          <title>Learn Grid</title>
          <meta name='description' content='Generated by create-t3-app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <main className='flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]'>
          <div className='container flex flex-col items-center justify-center gap-12 px-4 py-16 '>
            <h1 className='text-2xl'>{note}</h1>
          </div>
        </main>
      </>
    )
  } else {
    return <div>WebMidi Not Enabled</div>
  }
}

export default Home
